id: IC47A353F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T07:48:54+00:00'
last_modified: '2022-06-10T10:53:23.959576+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3416
  title: གསུང་འབུམ། སྡེ་སྤྲུལ་ཀུན་དགའ་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    186A:
      image_group_id: I3CN8606
      title: ''
      total_pages: 360
      order: 1
      base_file: 186A.txt
    399A:
      image_group_id: I3CN8607
      title: ''
      total_pages: 382
      order: 2
      base_file: 399A.txt
    C578:
      image_group_id: I3CN8608
      title: ''
      total_pages: 392
      order: 3
      base_file: C578.txt
    40B8:
      image_group_id: I3CN8609
      title: ''
      total_pages: 508
      order: 4
      base_file: 40B8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
